---
title: "data_rowbinding"
author: "Ines Vanagt"
date: "12 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this section, we will rowbind all the webscrapped dataset we have, in order to integrate them in a cleaner way to our package.

## Data rowbinding

#### Libraries import

```{r}
library(readr)
library(purrr)
library(tidyverse)
```

#### Data rowbinding

```{r}
all_files <- c("datasets/arnaud_scrapping.csv", 
               "datasets/scrapped_listings_1_1_500.csv",
               "datasets/scrapped_listings_1_501_750.csv",
               "datasets/scrapped_listings_1_751_1000.csv",
               "datasets/scrapped_listings_1_1000_1500.csv",
               "datasets/scrapped_listings_1_1501_2000.csv",
               "datasets/scrapped_listings_1_2001_2400.csv",
               "datasets/scrapped_listings_1_2401_3000.csv",
               "datasets/scrapped_listings_1_3001_4000.csv",
               "datasets/scrapped_listings_1_4001_4500.csv",
               "datasets/scrapped_listings_1_4501_5500.csv",
               "datasets/scrapped_listings_1_6501_7500.csv",
               "datasets/scrapped_listings_1_7501_8500.csv",
               "datasets/scrapped_listings_2_1_250.csv",
               "datasets/scrapped_listings_2_251_500.csv",
               "datasets/scrapped_listings_2_501_750.csv",
               "datasets/scrapped_listings_2_751_1000.csv",
               "datasets/scrapped_listings_3_1_250.csv",
               "datasets/scrapped_listings_3_251_500.csv",
               "datasets/scrapped_listings_3_501_750.csv",
               "datasets/scrapped_listings_3_751_1000.csv")

# Read all

all_df <- map(all_files, ~read_csv(.x))

# For one dataset, we have a different ordering of the columns ¯\_(ツ)_/¯

names(all_df[[1]]) <- c("X1","url","is_listing_deleted", "brand", "modele","address_particulier","address_pro","name_pro","Année","Autres informations","Carrosserie","Emissions de CO2", "Energie","Kilométrage", "Nb de portes", "Nombre de places", "Prix", "Puissance fiscale", "Puissance réelle", "Transmission", "V1", "Garantie mécanique", "Consommation mixte", "Contrôle technique", "Couleur intérieur", "Type de peinture carrosserie",  "Etat du véhicule", "Option equipement Sécurité", "Option/Equipement Confort intérieur", "Option/equipement extérieurs", "Marque")

# Row bind into data

webscrapped_data <- map_df(all_df, ~bind_rows(.x))
```

#### Writing the full original scrapped data csv

```{r}
write_csv(webscrapped_data, path = "datasets/original_scrapped_data_full.csv")
```

