---
title: "Regression"
author: "Arnaud Fournier"
date: "07/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(MASS)
library(glmnet)
library(stringr)
library(data.table)
library(purrr)
Sys.setlocale(locale="en_US.UTF-8")
```

```{r Load Data}
reg_data <- read_csv("archive/datasets/first_dataset_full.csv")
```



```{r, function shiny}

reg_shiny_function("Berline", reg_data)

reg_shiny_function <- function(carrosserie, df){
  
  carrosserie <- enquo(carrosserie) #enquo the variable
 
#Lets create the table we'll use later   
df_significant_coef <- tibble::rownames_to_column(as.data.frame(regression_function(df, !!carrosserie)$coef), "coef")#Create a data frame with no row naes as it is easier to work without


df_significant_coef <- df_significant_coef %>% 
        filter(coef!="(Intercept)") # Take out intercept as it doesnt matter for our study


#Long step, we change individually the name of oef for interpretation (couldn't do it in 1 mutatet as regression don't all have the same coefficients)
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieElectrique") %>% 
                      mutate(coef="electric car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieElectrique") 
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "kilometrage_km") %>% 
                      mutate(Estimate=Estimate*10000, coef="car with + 10'000 km") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "kilometrage_km")
                      
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieEssence") %>% 
                      mutate(coef="gasoline car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieEssence")
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieHybride") %>% 
                      mutate(coef="hybrid car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieHybride")      
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieGPL ou GNL") %>% 
                      mutate(coef="GPL car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieGPL ou GNL") 

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "transmissionAutres") %>% 
                      mutate(coef="unvonventional transmission type car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionAutres")
  
df_significant_coef  <- df_significant_coef %>%                       
                      filter(coef== "transmissionManuelle") %>% 
                      mutate(coef= "manual transmission car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionManuelle")
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "transmissionSemi automatique") %>% 
                      mutate(coef= "semi-automatic transmission car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionSemi automatique") 
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "is_pro") %>% 
                      mutate(coef= "car from a profresional seller") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "is_pro")

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "nb_portes4") %>% 
                      mutate(coef= "car with 4 doors") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "nb_portes4") 

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "nb_portes5") %>% 
                      mutate(coef= "car with 5 doors") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "nb_portes5") 

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "nb_portes") %>% 
                      mutate(coef= "car with one more door") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "nb_portes") 


df_significant_coef  <- df_significant_coef %>% 
                      filter(`Pr(>|t|)`<0.05) %>% #Filter for significant features only
                      dplyr::select(coef, Estimate)



#Split the significant coef into 2 separate table, the positive and the negative
#So that we can have different interpretation
positiv_coef <- df_significant_coef %>% filter(Estimate>0)
negativ_coef <- df_significant_coef %>% filter(Estimate<0)


negativ_coef <- negativ_coef %>% pmap_chr(.f= function(Estimate,coef){paste("If you switch to a",coef,"you could save about", -signif(Estimate,2), "€")})

positiv_coef <- positiv_coef %>% pmap_chr(.f= function(Estimate,coef){paste("If you switch to a", coef, "you would pay an extra", signif(Estimate,2), "€")})

return(c(negativ_coef,positiv_coef)) #Returns the two

}



regression_function <- function(data_reg, carrosserie){

  type_car <- enquo(carrosserie) #enquo the name of the type of car we wnt tu use in the reg
  
  data_reg <- data_reg %>% filter(carrosserie == !!type_car) #Filter the dataset for this type of car
  
  reg_sol <- lm(prix_euros  ~ energie + transmission+is_pro+kilometrage_km+nb_portes, data_reg) 
  return(summary(reg_sol))
}

```





###### Trash

```{r, function}


#Lets create the table we'll use later
df_significant_coef <- tibble::rownames_to_column(as.data.frame(regression_function(reg_data, "Break")$coef), "coef") 


#Create a data frame with no row naes as it is easier to work without
df_significant_coef <- df_significant_coef %>% 
        filter(coef!="(Intercept)")



df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieElectrique") %>% 
                      mutate(coef="electric car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieElectrique") 
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "kilometrage_km") %>% 
                      mutate(Estimate=Estimate*10000, coef="car with + 10'000 km") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "kilometrage_km")
                      



df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieEssence") %>% 
                      mutate(coef="gasoline car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieEssence")
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieHybride") %>% 
                      mutate(coef="hybrid car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieHybride")      
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "energieGPL ou GNL") %>% 
                      mutate(coef="GPL car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "energieGPL ou GNL") 

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "transmissionAutres") %>% 
                      mutate(coef="unvonventional transmission type car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionAutres")
  
df_significant_coef  <- df_significant_coef %>%                       
                      filter(coef== "transmissionManuelle") %>% 
                      mutate(coef= "manual transmission car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionManuelle")
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "transmissionSemi automatique") %>% 
                      mutate(coef= "semi-atomatic transmission car") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "transmissionSemi automatique") 
  
df_significant_coef  <- df_significant_coef %>% 
                      filter(coef== "is_pro") %>% 
                      mutate(coef= "car from a profresional seller") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "is_pro")

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "nb_portes4") %>% 
                      mutate(coef= "car with 4 doors") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "nb_portes4") 

df_significant_coef  <- df_significant_coef %>%   
                      filter(coef== "nb_portes5") %>% 
                      mutate(coef= "car with 5 doors") %>% 
                      bind_rows(df_significant_coef) %>% 
                      filter(coef != "nb_portes5") 


df_significant_coef  <- df_significant_coef %>% 
                      filter(`Pr(>|t|)`<0.05) %>% #Filter for significant features only
                      dplyr::select(coef, Estimate)





#Split the significant coef into 2 separate table, the positive and the negative
positiv_coef <- df_significant_coef %>% filter(Estimate>0)
negativ_coef <- df_significant_coef %>% filter(Estimate<0)



# Printing out the info for the shiny tab
paste("Want to save some money ? There are", length(negatif_coef$coef), "features that could help you")





negativ_coef %>% pmap_chr(.f= function(Estimate,coef){paste("Buying a",coef,"you could save about", -signif(Estimate,2), "€")})

positiv_coef %>% pmap_chr(.f= function(Estimate,coef){paste("With a",coef, "you would pay an extra", signif(Estimate,2))})











class(df_significant_coef)
regression_function(reg_data, "Break")$coefficient 

coef_function("Monospace", reg_data)













```

#data clearing

```{r}

#select only variables useful for our regression
reg_data <- reg_data %>% dplyr::select(prix_euros , brand, carrosserie, energie, transmission, is_pro, kilometrage_km, nb_portes, hayon, cons_mixte_l_by_100km)

#We need to have price to predict it so we delete rows where price is na, we also need the type of car for our shiny app
#I recoded nb_porte as a factor because it makes more sense
reg_data <- reg_data %>% 
  filter(!is.na(prix_euros), !is.na(carrosserie)) %>% 
  mutate(nb_portes=as.factor(nb_portes),
         cons_mixte_l_by_100km=as.numeric(cons_mixte_l_by_100km))




#We can get the list of type of car we can use in our app using this:
carrosserie_name <- function(df){

carrosserie <-   df %>%
  group_by(carrosserie) %>%
  summarise(n=n()) %>% 
  filter(n > 50, !is.na(carrosserie)) %>% 
  dplyr::select(carrosserie) %>% 
  as.list()
  return(carrosserie$carrosserie)
}  

carrosserie_name(reg_data)

```

```{r}

coef_function <- function(carrosserie, df){
  carrosserie <- as.character(carrosserie)
  carrosserie <- enquo(carrosserie)
  
  coef_0 <- regression_function(reg_data, !!carrosserie)$coef[1]
 coef_essence <- regression_function(reg_data, !!carrosserie)$coef[3]
  coef_hybride <- regression_function(reg_data, !!carrosserie)$coef[5]
  coef_manuelle <- regression_function(reg_data, !!carrosserie)$coef[7]
  coef_semi_auto <- regression_function(reg_data, !!carrosserie)$coef[8]
  coef_is_pro <- regression_function(reg_data, !!carrosserie)$coef[9]
  coef_kilom <- regression_function(reg_data, !!carrosserie)$coef[10]
 
  
  return(data_frame(coef_0,coef_essence,coef_hybride,coef_manuelle,coef_semi_auto,coef_is_pro,coef_kilom))
}


?coef
output_fonction <- function(){
  

  
  
}



?geom_bar
ggplot(reg_data)+aes(y=prix_euros,x=kilometrage_km)+geom_bar(stats="identity")

ggplot(reg_data)+aes(y=prix_euros,x=kilometrage_km)+geom_smooth()


?summary
?lm


```



### Model selection
```{r}
#tried doing a lasso before realissing it would nor be possible to interpret easily if we had to recode all factor variables into dummies and if only some brand were kept (as our aim is interpretation we decided to use a linear regression)


#testing the distribution of price
ggplot(reg_data) +aes(x = log(prix_euros))+geom_histogram(bins = 50)



#missing values management
missing_values <- as.data.frame(colSums(is.na(reg_data)))
colnames(missing_values) <- "x"

missing_values_uncleared <- colSums(is.na(reg_data))



#test of LASSO
glimpse(reg_data)

lam=seq(0,5,by=0.05)
?model.matrix
xfactor <- model.matrix(prix_euros ~ brand, energie, transmission , is_pro, nb_portes, hayon, data = reg_data)
x <- as.matrix()

beta.lasso=glmnet(x=c(prix_euros,modele, brand, carrosserie, energie, transmission, is_pro, kilometrage_km, nb_portes, hayon), y= prix_euros ,alpha=1,lambda=lam )

?glmnet

```




```{r}

#Test of different regression
reg_data_break <- reg_data %>% filter(carrosserie=="Break")
reg_sol_break <- lm(prix_euros  ~ energie+transmission+is_pro+kilometrage_km+nb_portes+hayon , reg_data_break)
summary(reg_sol_break)

reg_data_berlines <- reg_data %>% filter(carrosserie=="Berline")

reg_sol_berlines <- lm(prix_euros  ~ energie+transmission+is_pro+kilometrage_km+nb_portes+hayon , reg_data_berlines)
summary(reg_sol_berlines)

```


