---
title: "data_cleaning_for_noobs"
author: "gg"
date: "11/19/2018"
output: html_document
---

```{r}
library(tidyverse)
library(magrittr)
library(readr)
library(stringr)
library(lubridate)
library(purrr)
library(FactoMineR)
library(MASS)
library(glmulti)

Sys.setlocale(locale="en_US.UTF-8")
```


```{r fig.height=12, fig.width=12}
data <- read_csv("datasets/first_dataset_full.csv")

glimpse(data)

na_prop <- data.frame(
  data %>% 
  mutate_all(is.na) %>% 
  mutate_all(mean) %>% 
  head(1)
)

na_prop < 0.1

data_reg <- data%>% 
  select(
    brand,
    #modele,
    carrosserie,
    energie,
    transmission,
    #all_city,
    is_pro,
    date,
    kilometrage_km,
    nb_portes,
    hayon,
    prix_euros
  )
View(data_reg)

model <- lm(data_reg, formula = prix_euros ~.)

better_model <- lm(data_reg, formula = prix_euros~1+kilometrage_km:transmission+kilometrage_km:date+nb_portes:brand+nb_portes:carrosserie+nb_portes:energie+nb_portes:transmission+nb_portes:is_pro+nb_portes:date+nb_portes:kilometrage_km+hayon:brand+hayon:carrosserie)

summary(better_model)

pairs(data_reg %>% select_if(is.numeric))
```

```{r}

```

